### ISSUE TITLE
TODO: improvements

### ISSUE THREAD

**Issue by hansensalim** [DigitalCommons/land-explorer-back-end#3]
- [ ] General refactor for best practices.
- [ ] Graceful exceptions handling.
- [ ] Use DB transactions.
- [ ] Persistent error log (notification would be nice too).
- [ ] Await is currently being used for all async calls. Things like email API doesn't have to be blocking.
- [ ] API calls (e.g., email) should have a retry. Or even better, be a queued job that can be retried.
- [ ] Migration and seed for polygon database.
- [ ] Tests (unit, system, etc)
- [ ] Better typing (instead of "any" type).
- [ ] Reset password process should not be auto-generating and emailing plain text password to user.
- [ ] Polygon database may be moved to the server as the application.
- [ ] Don't use both import* & require(*)
